# jekyll config
safe:        true
lsi:         false
highlighter: pygments
permalink:   /news/:title/
exclude:     [vendor]
markdown:    redcarpet
redcarpet:
  extensions: [tables, with_toc_data]
gems:
  - jekyll-redirect-from

# custom config
cachebust: 1
